### ISSUE TITLE
Ver se é interessante travar rotação ao invés de apresentar tela cortada

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#102]
# Relatório de Bug

### Pré Requisitos
> Ter clicado no ícone do aplicativo
 
### Passos 
> Entrar no aplicativo e inverter o dispositivo deixando-o na horizontal

### Resultado esperado
> O aplicativo não deveria rotacionar sua tela.

### Evidencias 
> Virei o dispositivo e telas ficaram cortadas.
### Possível Solução 
> Travar rotação.

##### Ambiente: 
* [ ]  Produção
* [X]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
> 0.4

##### Outros artefatos:
> Testei em Tablet da UFPB e no meu Celular Galaxy S10

**Comment by LarrysaFigueiredo** [comment]
Sim! A tela permanece dando quebra de página na rotação deixando o aplicativo com uma aparência estranha e inutilizável. Telas testadas: 8000 x 6000 pixels e 720 x 1520 pixel.
