### ISSUE TITLE
Letras estão pequenas em algumas telas

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#103]
# Relatório de Bug

### Pré Requisitos
> Ter clicado no ícone do aplicativo.
 
### Passos 
> Acessar o menu do aplicativo e entrar nos níveis

### Resultado esperado
> Que o tamanho da letra esteja apropriado para diferentes tipos de dispositivo e que o usuário possa fazer zoom nas telas.

### Evidencias 
> Em algumas telas o título está pequeno, como no título da Tela de Sobre e em Cards de explicações.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/1224119/112868109-106aed00-9092-11eb-9288-f432e1ab5457.png">

![image](https://user-images.githubusercontent.com/1224119/112868177-237dbd00-9092-11eb-8092-271756bb7fb2.png)

### Possível Solução 
> Tentar adequar o tamanho da letra ao dispositivo ou ao menos permitir ao usuário que faça um zoom nas telas.

##### Ambiente: 
* [ ]  Produção
* [X]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
> 0.4

##### Outros artefatos:
> Foi utilizado o Tablet Samsung da Universidade para os testes, Mas em celular por vezes também fica pequena a letra e o zoom é interessante, como mostrado na imagem a seguir:
![image](https://user-images.githubusercontent.com/1224119/112868426-693a8580-9092-11eb-972c-55ee79095e9f.png)
.

**Comment by LarrysaFigueiredo** [comment]
@barbosamaatheus nos aparelhos com telas acima de 3 e 5 polegadas não tive problema em testar e não houve quebra de textos.

**Comment by ayladebora** [comment]
Pra mim no primeiro nível a letra ainda está menor do que no Nível 2, por exemplo. 
É interessante ter o ajuste também para alterar tamanho de letra de acordo com o dispositivo. No Tablet fica ainda maior a diferença entre a letra do Nível 1 e a do Nível 2
