### ISSUE TITLE
Ajuste no tamanho dos cards e no texto indicando para arrastar para o lado

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#22]
# Requisito

### Classificação
* [X]  Requisito Funcional (RF).
* [ ]  Requisito Não Funcional (RNF).

### Descrição
> Na primeira tela do nível 1 e em outras telas semelhantes (ex: 2a. tela), sugiro mudar a proporção deixando o card de baixo bem menor e reduzindo seu texto apenas para  "Arraste o card para o lado e verá as próximas instruções".  Creio que o texto "Leia atentamente cada questão..."  é desnecessário, até porque não são questões nesse ponto.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/1224119/106070316-ff7a1b80-60e2-11eb-9de0-1b85670575be.png">

**Comment by ayladebora** [comment]
O texto poderia ser "Arraste o card para o lado para continuar"

Telas a que me refiro:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/1224119/106072127-5fbe8c80-60e6-11eb-9a52-5d5be941da32.png">

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1224119/106072174-782ea700-60e6-11eb-872d-76d38acde738.png">

**Comment by emanoelmlsilva** [comment]
seria interessante trocar o texto, mas qual seria o tamanho da parte de baixo?
