### ISSUE TITLE
Rever concordância no texto de perguntas do nível 1 e ordem das telas que falam sobre fax

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#25]
# Relatório de Bug

### Pré Requisitos
> Estar no nível 1 do aplicativo
 
### Passos 
> Entrar no nível 1 e chegar à tela da pergunta sobre o que as máquinas de fax fazem.

### Resultado esperado
>Acredito que o texto explicando sobre máquinas de fax pode vir junto da outra pergunta e até como feedback dela. Além disso, deve ser revista a concordância das opções indicadas nessa página:

- Enviam vídeos
- Realizam contagens
- Sorteam números
- Imprimem pixels

### Evidencias 
> São apresentadas opções que não concordam com a pergunta

<img width="371" alt="image" src="https://user-images.githubusercontent.com/1224119/106073598-25a2ba00-60e9-11eb-82ce-a9c548864d92.png">

### Possível Solução 
> Ajustar texto das respostas e ver telas anteriores e esta atual considerando pergunta anterior já nesse tema de faz:

- Enviam vídeos
- Realizam contagens
- Sorteam números
- Imprimem pixels

##### Ambiente: 
* [ ]  Produção
* [X]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
>  v1.0.0-2

**Comment by barbosamaatheus** [comment]
Problema não ocorre mais segundo @josinaldojr
