### ISSUE TITLE
Rever se é necessária a tela com a pergunta com opções de código morse/regex

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#26]
# Relatório de Bug

### Pré Requisitos
>Estar no nível 1 do aplicativo
 
### Passos 
> Entrar no nível 1 e chegar até a tela com a pergunta sobre armazenamento da informação com dígitos

### Resultado esperado
> Sugiro tirar essa tela/pergunta ou rever a pergunta feita.

### Evidencias 
> Tela que acredito que poderia sair.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1224119/106074002-dc9f3580-60e9-11eb-8dff-9bac8ef26695.png">

### Possível Solução 
> Sugiro tirar essa tela/pergunta ou rever a pergunta feita.

##### Ambiente: 
* [ ]  Produção
* [x]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
>  v1.0.0-2

**Comment by emanoelmlsilva** [comment]
ficou estanho essa pergunta, poderia reformular ela para algo como "Como os computadores representam as imagens que eles armazenam?"
