### ISSUE TITLE
Aumentar o tempo de feedback do nivel 1

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#27]
# Relatório de Bug

### Pré Requisitos
> Concluir o nível 1
 
### Passos 
> Terminar os passos do nível 1

### Resultado esperado
> Ter tempo suficiente para ler as mensagens de feedback do fim do nível 1.

### Evidencias 
> Não dá tempo de ler o texto desse nível. 

### Possível Solução 
> Poderia-se aumentar o tempo de exibição da tela ou inserir botão de "Seguir para o Nível 2"

##### Ambiente: 
* [ ]  Produção
* [X]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
>  v1.0.0-2

**Comment by ayladebora** [comment]
Percebi agora que há até o "Continuar", mas o contraste tá ruim (não utilizar letra azul em fundo preto). Creio que o "Continuar". poderia ser um botão bonito. Pode talvez ter fundo branco e cor da fonte Azul.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/1224119/106080688-5a693e00-60f6-11eb-98ee-b0fdd37dd45e.png">

**Comment by emanoelmlsilva** [comment]
Corrigido na issue #39
