### ISSUE TITLE
Rever se é necessária a tela 8 do nível 1 sobre situações para armazenar imagens

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#28]
# Relatório de Bug

### Pré Requisitos
> Estar no nível 1
 
### Passos 
> Avançar no nível 1 até a tela 8

### Resultado esperado
> Rever a pergunta a utilizar ou talvez apenas remover esta tela

### Evidencias 
>Tela que poderia ser removida

<img width="371" alt="image" src="https://user-images.githubusercontent.com/1224119/106080007-0e69c980-60f5-11eb-83c9-8b057f8e5782.png">

### Possível Solução 
> Remover a tela indicada ou rever a pergunta

##### Ambiente: 
* [ ]  Produção
* [X]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
> v1.0.0-2

**Comment by emanoelmlsilva** [comment]
seria bom retirar essa questão, não está seguindo o mesmo sentido das outras.
