### ISSUE TITLE
Ajuste no texto da tela de Sobre sobre Copyright

### ISSUE THREAD

**Issue by ayladebora** [pluggedcomputing/pixel#41]
# Relatório de Bug

### Pré Requisitos
> Entrar no aplicativo
 
### Passos 
> Entrar no aplicativo e clicar no botão "Sobre"

### Resultado esperado
> Tirar texto sobre "Todos os Direitos Reservados 2020" já que ainda não registramos propriedade ou ao menos mudar para 2021. Sugiro também colocar "Campus" com "C" maiúsculo.

### Evidencias 
> Tela atual:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1224119/106138371-d1302680-614a-11eb-81ee-4eea8ea7ad1b.png">

### Possível Solução 
> Tirar texto sobre "Todos os Direitos Reservados 2020" já que ainda não registramos propriedade ou ao menos mudar para 2021. Sugiro também colocar "Campus" com "C" maiúsculo.

##### Ambiente: 
* [ ]  Produção
* [X]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
> V1.0.0.2

**Comment by barbosamaatheus** [comment]
O correto deve ser remover o copyright e adicionar um link para a licensa no github.  https://github.com/pluggedcomputing/pixel/blob/develop/LICENSE

Usar método do javascript para obter o ano automaticamente.
