### ISSUE TITLE
Melhoria de Texto em alternativas na tela 11 nível 1

### ISSUE THREAD

**Issue by LarrysaFigueiredo** [pluggedcomputing/pixel#72]
# Relatório de Bug

### Pré Requisitos
1 - Está no aplicativo.
 
### Passos 
1 - Está no aplicativo;
2 - Acessar o nível 1;
3 - Ir a tela 11.

### Resultado esperado
Trocar a alternativa: “Os números tem que possuir uma sequência exata.” por “Por meio de números na base octal”.

### Evidencias 
![Captura de tela 2021-02-25 214849- tela 11](https://user-images.githubusercontent.com/54331880/109239289-e46afc00-77b3-11eb-9089-79424a798ac6.png)

### Possível Solução 
Conforme citado em Resultados Esperados.

##### Ambiente: 
* [ ]  Produção
* [x ]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

**Comment by emanoelmlsilva** [comment]
Coloquei dessa forma as alternativas.

![edit](https://user-images.githubusercontent.com/31074317/109691347-1ab6cb80-7b66-11eb-8cb6-ed38192a31a8.png)
