### ISSUE TITLE
Pergunta com resposta no nível 2 tela 4

### ISSUE THREAD

**Issue by LarrysaFigueiredo** [pluggedcomputing/pixel#77]
# Relatório de Bug

### Pré Requisitos
1 - Está no aplicativo 
 
### Passos 
1 - Está no aplicativo;
2 - Ir para o nível 2;
3 - Está na tela 4.

### Resultado esperado
Pergunta sem a resposta e que a mesma só seja dada ao usuário quando o mesmo selecionar uma das alternativas.

### Evidencias 
![Captura de tela 2021-02-25 222749 - nv2 tela 4 com resposta](https://user-images.githubusercontent.com/54331880/109241923-ee432e00-77b8-11eb-8f5f-431f8eabbb88.png)

### Possível Solução 
Retirada da reposta.

##### Ambiente: 
* [ ]  Produção
* [x ]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

**Comment by emanoelmlsilva** [comment]
não esta acontecendo aqui no meu @LarrysaFigueiredo

**Comment by ayladebora** [comment]
Na verdade pra mim aconteceu às vezes de voltar e uma que estaria respondida não estava mais marcada a resposta.

**Comment by barbosamaatheus** [comment]
@emanoelmlsilva @ayladebora @LarrysaFigueiredo algum pode ver se esse problema ainda ocorre? por favor

**Comment by LarrysaFigueiredo** [comment]
> @emanoelmlsilva @ayladebora @LarrysaFigueiredo algum pode ver se esse problema ainda ocorre? por favor

Não @barbosamaatheus nesta nova versão, aparentemente está funcionando normal!

**Comment by LarrysaFigueiredo** [comment]
A tela em questão deveria apresentar a letra W e qual linha representaria a que está em falta na imagem.
