### ISSUE TITLE
Sobreposição de Tela no nivel 2 tela 5

### ISSUE THREAD

**Issue by LarrysaFigueiredo** [pluggedcomputing/pixel#78]
# Relatório de Bug

### Pré Requisitos
1 - Está no aplicativo
 
### Passos 
1 - Está no aplicativo;
2 - Ir para o nível 2;
3 - Está na tela 5.

### Resultado esperado
A pergunta deverá está de acordo com a tela. Pois a tela 5 é mostrada com a pergunta anterior.

### Evidencias 
![Captura de tela 2021-02-25 223037 tela 5 nv 2](https://user-images.githubusercontent.com/54331880/109242203-6d386680-77b9-11eb-840c-83e9f82ab004.png)

### Possível Solução 
Verificação do código.

##### Ambiente: 
* [ ]  Produção
* [ x ]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

**Comment by ayladebora** [comment]
Confirmo que o bug continua acontecendo na versão 0.4

**Comment by ayladebora** [comment]
Às vezes essa tela nem é mostrada pra mim às vezes. Acontece a sobreposição da Tela 4 do Nível 2 com as opções da Tela 5.
