### ISSUE TITLE
Sobreposição de tela no nível  tela 4

### ISSUE THREAD

**Issue by LarrysaFigueiredo** [pluggedcomputing/pixel#81]
# Relatório de Bug

### Pré Requisitos
1 - Está no aplicativo;
 
### Passos 
1 - Está no aplicativo;
2 - Ir para o nível 3;
3 - Está na tela 4;

### Resultado esperado
Ao responder a pergunta da tela 4 a mesma fosse substituida pela tela 5 para continuação do uso do app.

### Evidencias 
![Captura de tela 2021-02-25 230051 - incorreta - tela 4](https://user-images.githubusercontent.com/54331880/109244436-788d9100-77bd-11eb-9914-2db8a7fe68c5.png)  tela que permaneceu mesmo após respondida.

![Captura de tela 2021-02-25 230129 - tela correta - Nivel 3 tela 4](https://user-images.githubusercontent.com/54331880/109244484-8e9b5180-77bd-11eb-9953-45272c732f65.png)
 Tela que deveria ter aparecido em sequencia a reposta.

### Possível Solução 
-

##### Ambiente: 
* [ ]  Produção
* [ x ]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

**Comment by ayladebora** [comment]
Confirmo que o problema acontece na versão 0.4
