### ISSUE TITLE
Sobreposição de tela nas telas 5 e 6 nivel 3

### ISSUE THREAD

**Issue by LarrysaFigueiredo** [pluggedcomputing/pixel#84]
Pré Requisitos
1 - Está no aplicativo

Passos
1 - Está no aplicativo;
2 - Ir para o nível 3;
3 - Está na tela 6.

Resultado esperado
A pergunta deve está de acordo com as repostas, porém aparece a 6 pergunta mas com as repostas da 5.

Evidencias
![Captura de tela 2021-02-25 231250- nv3 tela 6](https://user-images.githubusercontent.com/54331880/109245356-146bcc80-77bf-11eb-9d93-9dbd7c12e4a5.png) Tela que aparece

![Captura de tela 2021-02-25 231725 correta](https://user-images.githubusercontent.com/54331880/109245680-b986a500-77bf-11eb-8319-3ee70b537e05.png)
Tela correta

### Possível Solução 
Correção da sobreposição

##### Ambiente: 
* [ ]  Produção
* [ x ]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

**Comment by ayladebora** [comment]
Confirmo que o bug continua acontecendo na versão 0.4
